import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased mdl-js">
      <body>
        <div className="flex min-h-svh flex-col text-base-content overflow-hidden">
          <Navbar />
          <main className="mx-auto w-full max-w-7xl flex-1 px-4 md:px-6 xl:px-0">
            <Layout children={children} />
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
